---
- name: Installing formula packages
  community.general.homebrew:
    name: "{{ brew.formula_packages }}"
    state: present

- name: Installing cask packages
  community.general.homebrew_cask:
    name: "{{ brew.cask_packages }}"
    state: present

- name: Installing fonts
  community.general.homebrew_cask:
    name: "{{ brew.fonts }}"
    state: present
