---
dependency:
  name: galaxy
  enabled: false
driver:
  name: docker
platforms:
  - name: instance
    image: sickcodes/docker-osx:ventura
    pre_build_image: true
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
