---
- name: Ensure ghostty config directory exists
  ansible.builtin.file:
    path: "{{ ghostty.config.dest | dirname }}"
    state: directory
    mode: "0755"

- name: Create config file
  ansible.builtin.template:
    src: "{{ ghostty.config.template }}"
    dest: "{{ ghostty.config.dest }}"
