---
- name: Ensure ghostty config directory exists
  ansible.builtin.file:
    path: "~/.config/ghostty"
    state: directory
    mode: "0755"

- name: Copy config file
  ansible.builtin.copy:
    src: "config"
    dest: "~/.config/ghostty/config"
    mode: "0644"
