---
- name: Ensure config directory exists
  ansible.builtin.file:
    path: "~/.config/zed"
    state: directory
    mode: "0700"

- name: Copy settings.json
  ansible.builtin.copy:
    src: "settings.json"
    dest: "~/.config/zed/settings.json"
    mode: "0644"

- name: Copy keymap.json
  ansible.builtin.copy:
    src: "keymap.json"
    dest: "~/.config/zed/keymap.json"
    mode: "0644"
