---
- name: 1password > Ensure .1password directory exists
  ansible.builtin.file:
    path: "{{ ssh.agent.dir }}"
    state: directory
    mode: "0700"

- name: 1password > Create symlink to ssh agent
  ansible.builtin.file:
    src: "{{ ssh.agent.sock }}"
    dest: "{{ ssh.agent.auth_sock }}"
    state: link
    force: true
