---
- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: "{{ ssh.dir }}"
    state: directory
    mode: "0700"

- name: Check if SSH key exists
  ansible.builtin.stat:
    path: "{{ ssh.key_path }}"
  register: ssh_key_file

- name: Generate SSH key if not exists
  ansible.builtin.command:
    cmd: ssh-keygen -t ed25519 -f {{ ssh.key_path }} -N "{{ vault.ssh.passphrase | default('') }}" -C "{{ vault.git.email }}"
  when: not ssh_key_file.stat.exists

- name: Create SSH config file
  ansible.builtin.template:
    src: "{{ ssh.config.template }}"
    dest: "{{ ssh.config.dest }}"
    mode: "0644"

- name: Ensure known_hosts file exists
  ansible.builtin.file:
    path: "{{ ssh.known_hosts }}"
    state: touch
    mode: "0644"
