---
- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: "{{ ssh.dir }}"
    state: directory
    mode: "0700"

- name: Create ssh config file
  ansible.builtin.template:
    src: "{{ ssh.config.template }}"
    dest: "{{ ssh.config.dest }}"
    mode: "0644"

- name: Add github.com key to known_hosts
  ansible.builtin.known_hosts:
    name: github.com
    key: "{{ ssh.host_keys.github }}"
    state: present
    path: "{{ ssh.known_hosts }}"

- name: Discovery tasks
  ansible.builtin.include_tasks:
    file: 1password.yml
