---
- name: Installing cask packages
  community.general.homebrew:
    name: "{{ brew.cask_packages }}"
    state: present
    install_options: ["cask"]

- name: Installing fonts
  community.general.homebrew:
    name: "{{ brew.fonts }}"
    state: present
    install_options: ["cask"]
