---
- name: Installing zsh
  community.general.homebrew:
    name: "zsh"
    state: present

- name: Disable login banner
  ansible.builtin.file:
    path: "~/.hushlogin"
    state: touch
    mode: "0644"

- name: Discovery tasks
  ansible.builtin.include_tasks:
    file: oh_my_zsh.yml
