---
- name: Oh-my-zsh > Check that the omz installer exists
  ansible.builtin.stat:
    path: "{{ omz.installer.dest }}"
  register: installer

- name: Oh-my-zsh > Download install script
  ansible.builtin.get_url:
    url: "{{ omz.installer.url }}"
    dest: "{{ omz.installer.dest }}"
    mode: "0755"
  when: not installer.stat.exists

- name: Oh-my-zsh > Check if oh-my-zsh is installed
  ansible.builtin.stat:
    path: "~/.oh-my-zsh"
  register: omz_installed

- name: Oh-my-zsh > Installing oh-my-zsh
  ansible.builtin.shell:
    cmd: "{{ omz.installer.dest }}"
    executable: /bin/sh
  when: not omz_installed.stat.exists
  changed_when: not omz_installed.stat.exists

- name: Oh-my-zsh > Check plugins installation status
  ansible.builtin.stat:
    path: "{{ omz.plugins }}/{{ item.name }}"
  loop:
    - { name: "zsh-syntax-highlighting", repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git" }
    - { name: "zsh-autosuggestions", repo: "https://github.com/zsh-users/zsh-autosuggestions.git" }
    - { name: "zsh-history-substring-search", repo: "https://github.com/zsh-users/zsh-history-substring-search.git" }
    - { name: "zsh-completions", repo: "https://github.com/zsh-users/zsh-completions.git" }
  register: zsh_plugins_status

- name: Oh-my-zsh > Install plugins
  ansible.builtin.git:
    repo: "{{ item.item.repo }}"
    dest: "{{ omz.plugins }}/{{ item.item.name }}"
    version: master
    depth: 1
  loop: "{{ zsh_plugins_status.results }}"
  when: not item.stat.exists

- name: Oh-my-zsh > Check themes installation status
  ansible.builtin.stat:
    path: "{{ omz.themes }}/{{ item.name }}"
  loop:
    - { name: "powerlevel10k", repo: "https://github.com/romkatv/powerlevel10k.git" }
  register: zsh_themes_status

- name: Oh-my-zsh > Install themes
  ansible.builtin.git:
    repo: "{{ item.item.repo }}"
    dest: "{{ omz.themes }}/{{ item.item.name }}"
    version: master
    depth: 1
  loop: "{{ zsh_themes_status.results }}"
  when: not item.stat.exists

- name: Oh-my-zsh > Copy p10k.zsh configuration
  ansible.builtin.copy:
    src: ".p10k.zsh"
    dest: "~/.p10k.zsh"
    mode: "0644"

- name: Oh-my-zsh > Copy .zshrc
  ansible.builtin.copy:
    src: ".zshrc"
    dest: "~/.zshrc"
    mode: "0644"
