name: ansible-lint
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run ansible-lint
        uses: ansible/ansible-lint-action@main
        with:
         path: "${{ github.workspace }}/andrew-kandyba/dotfiles/ansible/playbook.yml"
