name: ansible-lint
on: [push, pull_request]
jobs:
  build:
    name: Ansible lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint in docker
        uses: docker://pipelinecomponents/ansible-lint:latest
        with:
          entrypoint: ansible-lint
          args: "--config-file=.ansible-lint ansible/"
